### ISSUE TITLE
Docker image is currently broken

### ISSUE THREAD

**Issue by thoughtpolice** [supabase/nix-postgres#13]
The current Docker image in `main` doesn't work right, because PostgreSQL doesn't want to run as `root` under Docker. This is understandable but it throws a wrench in the engine because it's difficult to get a proper image container set up in the way Docker wants. This isn't insurmountable, but it will take more work than I expected to sort out.

The issue is a complex one due to the way cgroups, docker, etc all interact. The long and short of it is that we need `root` to build a properly functioning container with proper `/etc` setup for user lookups and authentication in PostgreSQL, because it users Unix authentication infrastructure by default. However, you typically need `uid=0` (root) in order to do that, because certain files need to be owned by root. All nix builds happen using custom users however that do not have root permissions; so when you try to create a container image, you can't set `uid=0` on a file properly. So this gets complicated quickly.

#12 *does* create a working image, but it does so in a rather absurd way: it launches a VM internally in order to mount files into a container with `uid=0`, then exports those files outside of the VM. This can't work on GitHub Actions, however, because nested virtualization isn't supported here.

There are a couple options at this point.

## Use custom runners that have KVM

Supabase has custom ARM and x86_64 runners which could do this. They need:

- To have Nix installed (probably via [nix-installer](https://github.com/DeterminateSystems/nix-installer)), and
- To have KVM virtualization available on the host

If these are satisfied, the workflows can probably be adapted to run the builds on those machines. It is unclear what changes will be needed, but I suspect it would take some fiddling.

## Find another way

Ideally, we could actually just build a functioning container *without* all that, but I spent a bunch of time on Friday trying various things and sort of came up empty handed. Honestly, this is something that I think PostgreSQL itself should handle better since containerization is so important these days. On the other hand, most people just use Docker, and Docker just avoids the whole thing because the Docker daemon runs as effective `uid=0`, meaning that it *can* install files with the right permissions, so it's all a bit of a mess because the incidental way docker works is what makes it all seem like it's OK.

### Possible solution: user namespaces?

User namespaces might be a way to do this since they would allow a container to think it is privileged, but they were for a time seen as a major security liability and it's unclear if that has changed. That means you may not be able to rely on them being available.

**Comment by samrose** [comment]
basically resolved with #45
