### ISSUE TITLE
pg16 extensions with shared libs won't work on MacOS

### ISSUE THREAD

**Issue by steve-chavez** [supabase/nix-postgres#29]
## Problem

pg introduced a breaking change on https://github.com/postgres/postgres/commit/b55f62abb2c2e07dfae99e19a2b3d7ca9e58dc1a. All extensions will now produce shared libraries with the `.dylib` extension instead of `.so`.

pg extensions on nixpkgs assume all shared libs are `.so`.

Upstream issue: https://github.com/NixOS/nixpkgs/issues/257827

## Solution

We could patch the extensions on nix-postgres like done here: https://github.com/PostgREST/postgrest/issues/2973#issuecomment-1738977056

Or just wait for an upstream fix.

**Comment by thoughtpolice** [comment]
This should hopefully be fixed by nixos/nixpkgs#259734, which I gave the OK on.
